const { snapshot } = require('./docxKnowledgeBase');
const RULES = `You are the PocketFM Promo Script Evaluator. Follow the supplied source and benchmark evidence. Score exactly these nine parameters from 1-10 with weights: sourceCharacterFidelity .15, hook .20, contextWorldClarity .10, sequencePlotMovement .10, sceneDesign .15, pacingTransitions .10, endingCallbackCta .10, narrationDialogueBalance .05, mentalImpactRecall .05. Final score is the weighted sum rounded to one decimal. P0 >=8.5, P1 >=6.5, otherwise P2. Hard checks: hook <=13 words, dialogue chunks <=25 words, exactly 3-4 specific CTA questions, Pocket FM mention, unresolved ending, Episode 1 callback when possible. Penalize contradictions and generic hooks. Return JSON only and use the exact schema requested. For every parameter below 7, suggestions must contain exactly five materially different actionable options, each with approach, rewriteOrFix, and reason. Never copy benchmark text.`;
function json(text) { const m = text.match(/\{[\s\S]*\}/); if (!m) throw new Error('OpenAI returned invalid JSON'); return JSON.parse(m[0]); }
async function call(prompt) {
  if (!process.env.OPENAI_API_KEY) throw new Error('OPENAI_API_KEY is not configured on the backend.');
  const r = await fetch('https://api.openai.com/v1/chat/completions', { method: 'POST', headers: { Authorization: `Bearer ${process.env.OPENAI_API_KEY}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ model: process.env.OPENAI_MODEL || 'gpt-5', messages: [{ role: 'system', content: RULES }, { role: 'user', content: prompt }], temperature: 0.2, response_format: { type: 'json_object' } }) });
  if (!r.ok) throw new Error(`OpenAI request failed (${r.status})`); const d = await r.json(); return json(d.choices[0].message.content);
}
const schema = `Schema for one evaluation: {overallScore:number,tier:"P0"|"P1"|"P2",tierLabel:string,sourceFidelityPercent:number,parameterScores:{sourceCharacterFidelity:{score:number,feedback:string,evidence:string[]},hook:{score:number,feedback:string,evidence:string[]},contextWorldClarity:{score:number,feedback:string,evidence:string[]},sequencePlotMovement:{score:number,feedback:string,evidence:string[]},sceneDesign:{score:number,feedback:string,evidence:string[]},pacingTransitions:{score:number,feedback:string,evidence:string[]},endingCallbackCta:{score:number,feedback:string,evidence:string[]},narrationDialogueBalance:{score:number,feedback:string,evidence:string[]},mentalImpactRecall:{score:number,feedback:string,evidence:string[]}},strongestElements:{hook:string,scene:string,characterMoment:string,ending:string},detectedStructure:"Original"|"Flashback"|"Jumbled",contradictions:string[],whatIsWorking:string[],weakPoints:[{issue:string,whyItFails:string,location:string}],suggestionsByParameter:{parameter:string,suggestions:[{approach:string,rewriteOrFix:string,reason:string}]}[],mentalImpactAssessment:string,publishRecommendation:string}`;
async function evaluateScript(script, show, genre, range) { const s = snapshot(show, genre, range); return call(`Evaluate ${show} (${genre}), source window ${s.episodeRange}. ${schema}\nSOURCE EVIDENCE:\n${s.source}\nBENCHMARK PATTERNS (use as evidence, not copy):\n${s.promos.map(p => p.text).join('\n---\n')}\nPROMO:\n${script}`); }
async function compareScripts(a, b, show, genre, range) { const s = snapshot(show, genre, range); return call(`Compare Promo A and B for ${show} (${genre}) using this identical source window and benchmarks. Return {promoA:${schema},promoB:${schema},deltas:object,winnerPerParameter:object,overallWinner:string,fidelityComparison:string,contradictionComparison:string,differences:string[],combinedRecommendation:string}. SOURCE:\n${s.source}\nBENCHMARKS:\n${s.promos.map(p => p.text).join('\n---\n')}\nPROMO A:\n${a}\nPROMO B:\n${b}`); }
module.exports = { evaluateScript, compareScripts };
